
GENERAL:
  seeds: 
    - 1

PGLIB_OPF:
  path: "/Projects/pglib-opf/"
  cases:
    - pglib_opf_case24_ieee_rts
    - pglib_opf_case57_ieee
    # - pglib_opf_case118_ieee

DATA:
  num_samples: 1000
  alpha: 0.2
  splits: 
    - 0.8
    - 0.1

PARAMETERS:
  GLOBAL:
    regression: true 
    local: false
    nmo: false
    batch_size: 10
    learning_rate: 0.001
    use_cuda: false
    num_epochs: 10
  FULLY_CONNECTED:
    active: true
    CONFIG:
      num_layers: 3
      drop_out: 0.5
  CONVOLUTIONAL:
    active: true
    CONFIG:
      num_layers: 3
      drop_out: 0.5
      kernel: 3
      pad: 1
      pool: 2
  GRAPH:
    active: true
    CONFIG:
      num_layers: 3
      drop_out: 0.5
