
GENERAL:
  seeds: 
    - 1

MODEL:
  regression: true 
  local: false
  ARCHITECTURE:
    fully_connected: true
    convolutional: false
    graph: false

PGLIB_OPF:
  path: "/Projects/pglib-opf/"
  cases:
    - pglib_opf_case24_ieee_rts
    # - pglib_opf_case57_ieee
    # - pglib_opf_case118_ieee

DATA:
  num_samples: 500
  alpha: 0.2
  splits: 
    - 0.8
    - 0.1

PARAMETERS:
  batch_size: 10
  learning_rate: 0.001
  use_cuda: false
  num_layers: 3
  drop_out: 0.1
  num_epochs: 200



